#!/usr/bin/env node
// Generate Prover.toml for circuits/mdl/kr from an OmniOne CX response.
//
// Usage:
//   node scripts/gen_prover_toml.mjs [--input <oacx-response.json>] [--flags 0x0F]
//                                    [--scope "openstoa:login:v1"]
//                                    [--region "경기도"] [--current-year 2026]
//                                    [--age-threshold 19]
//
// If no --input is given, the embedded demo response (hyun 운전면허) is used.

import sha3 from 'js-sha3';
const { keccak256 } = sha3;
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { argv, exit } from 'node:process';
import { randomBytes } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CIRCUIT_DIR = dirname(__dirname);

// ───────────────────────────────────────────────
// CLI args
// ───────────────────────────────────────────────
const args = Object.fromEntries(
  argv.slice(2).reduce((acc, a, i, arr) => {
    if (a.startsWith('--')) acc.push([a.slice(2), arr[i + 1]]);
    return acc;
  }, []),
);

const FLAGS_HEX   = args['flags']         ?? '0x0F';
const SCOPE_STR   = args['scope']         ?? 'openstoa:login:v1';
const REGION      = args['region']        ?? '경기도';
const CURR_YEAR   = parseInt(args['current-year']   ?? '2026', 10);
const AGE_THRESH  = parseInt(args['age-threshold']  ?? '19',   10);

const DEMO_RESPONSE = {
  ci: '258NYBwTVSUV7ph8dL55wJXVkalUCp1xiVqm5pIxVEY1wiq2/4uCH0QjI2rQKSXG1wQ9q/Z0+s5NlQHzJva+iQ==',
  name: '현제혁',
  birth: '19850130',
  telno: '01046564126',
  sex: '',
  jti: '6c53fdbc92be40388afc649166cb71419dhga1oi',
  pri: 'kJfvI0WelD8x9c29ab8ep3z1H8mHkn+91yTM3XbcKUw=',
};

const inputPath = args['input'];
const oacx = inputPath ? JSON.parse(readFileSync(inputPath, 'utf8')).data : DEMO_RESPONSE;

// ───────────────────────────────────────────────
// Helpers
// ───────────────────────────────────────────────
const k256 = (bytes) => Buffer.from(keccak256.arrayBuffer(new Uint8Array(bytes)));

const padZero = (input, totalLen, encoding = 'utf8') => {
  const buf = Buffer.from(input, encoding);
  if (buf.length > totalLen) {
    throw new Error(`Input "${input}" exceeds ${totalLen} bytes (got ${buf.length})`);
  }
  return Buffer.concat([buf, Buffer.alloc(totalLen - buf.length)]);
};

const tomlArray = (bytes) => '[' + Array.from(bytes).join(', ') + ']';

// ───────────────────────────────────────────────
// Fixed-size buffers (must match circuit globals)
// ───────────────────────────────────────────────
const ci   = padZero(oacx.ci,   88, 'utf8');   // base64 ASCII string
const jti  = padZero(oacx.jti,  40, 'utf8');
const pri  = padZero(oacx.pri,  44, 'utf8');
const name  = padZero(oacx.name,  64, 'utf8');
const telno = padZero(oacx.telno, 16, 'utf8');
const sex   = oacx.sex && oacx.sex.length > 0 ? oacx.sex.charCodeAt(0) : 0;
const birth = padZero(oacx.birth, 8,  'utf8');
const region = padZero(REGION, 64, 'utf8');

// ───────────────────────────────────────────────
// Public inputs (computed)
// ───────────────────────────────────────────────
const cx_integrity_root = k256(Buffer.concat([jti, pri]));

const mdl_buf = Buffer.concat([ci, jti, pri]);  // 88 + 40 + 44 = 172
const mdl_commit = k256(mdl_buf);
const self_id_20 = mdl_commit.subarray(0, 20);

const scope = k256(Buffer.from(SCOPE_STR, 'utf8'));
const signal_hash = randomBytes(32);

const user_secret = k256(Buffer.concat([self_id_20, signal_hash]));
const nullifier_value = k256(Buffer.concat([user_secret, scope]));

const region_code = k256(region);

const disclose_flags = parseInt(FLAGS_HEX, 16);

// Owner buffer (masked per flag)
const owner_buf = Buffer.alloc(89);
if (disclose_flags & 0x01) name.copy(owner_buf, 0);     // name [0..64]
if (disclose_flags & 0x02) birth.copy(owner_buf, 64);   // birth [64..72]
if (disclose_flags & 0x04) owner_buf[72] = sex;         // sex  [72]
if (disclose_flags & 0x08) telno.copy(owner_buf, 73);   // telno [73..89]

let owner_commit;
if (disclose_flags === 0) {
  owner_commit = Buffer.alloc(32);
} else {
  const commit_buf = Buffer.concat([Buffer.from([disclose_flags]), owner_buf]);
  owner_commit = k256(commit_buf);
}

// ───────────────────────────────────────────────
// Emit Prover.toml
// ───────────────────────────────────────────────
const lines = [
  '# Auto-generated by scripts/gen_prover_toml.mjs',
  '# Demo data: Korean mobile driver license (comdl), region "경기도"',
  '',
  '# ============ Public Inputs ============',
  `signal_hash       = ${tomlArray(signal_hash)}`,
  `scope             = ${tomlArray(scope)}`,
  `nullifier_value   = ${tomlArray(nullifier_value)}`,
  `cx_integrity_root = ${tomlArray(cx_integrity_root)}`,
  `age_threshold     = ${AGE_THRESH}`,
  `current_year      = ${CURR_YEAR}`,
  `region_code       = ${tomlArray(region_code)}`,
  `disclose_flags    = ${disclose_flags}`,
  `owner_commit      = ${tomlArray(owner_commit)}`,
  '',
  '# ============ Private Inputs ============',
  `ci          = ${tomlArray(ci)}`,
  `cx_jti      = ${tomlArray(jti)}`,
  `cx_pri      = ${tomlArray(pri)}`,
  `name        = ${tomlArray(name)}`,
  `birth_date  = ${tomlArray(birth)}`,
  `telno       = ${tomlArray(telno)}`,
  `sex         = ${sex}`,
  `region      = ${tomlArray(region)}`,
  '',
];

const outPath = join(CIRCUIT_DIR, 'Prover.toml');
writeFileSync(outPath, lines.join('\n'));

console.log('Wrote:', outPath);
console.log('');
console.log('Summary:');
console.log('  disclose_flags    =', '0x' + disclose_flags.toString(16).padStart(2, '0'));
console.log('  cx_integrity_root =', '0x' + cx_integrity_root.toString('hex'));
console.log('  self_id_20        =', '0x' + self_id_20.toString('hex'));
console.log('  nullifier_value   =', '0x' + nullifier_value.toString('hex'));
console.log('  scope             =', '0x' + scope.toString('hex'));
console.log('  signal_hash       =', '0x' + signal_hash.toString('hex'), '(random)');
console.log('  region_code       =', '0x' + region_code.toString('hex'));
console.log('  owner_commit      =', '0x' + owner_commit.toString('hex'));
