[package]
name = "zktls"
type = "bin"
authors = ["zkproofport"]
compiler_version = ">=1.0.0"

[dependencies]
pluto_aes_gcm = { path = "../deps/pluto-aes-gcm" }
keccak256 = { path = "../deps/keccak256" }
poseidon = { path = "../deps/poseidon" }
