#!/bin/bash
# Acceptance run for a circuit that signs an EIP-712 action OR a signal hash.
#
# Both `arc_eligibility` and `giwa_attestation` work this way, so this runs for
# either: pass the circuit directory. It was written for GIWA alone and moved
# here the moment Arc gained the same branch -- two copies of an acceptance run
# is how two circuits come to be checked to different standards.
#
# WHAT IT PROVES. Both modes are exercised against a REAL attestation
# transaction, so the raw EIP-1559 parsing and the attester key recovery are
# checked against bytes a chain actually holds rather than bytes we invented.
# The refusals matter as much: a circuit that accepts the happy fixture and
# also accepts a tampered one has not been tested, it has been demonstrated.
#
# Each refusal is derived from a committed-nowhere fixture by rewriting ONE
# field, and `tamper-fixture.js` refuses to write a file when the rewrite would
# change nothing -- a "tamper" that tampers with nothing would pass for the
# wrong reason. No network is needed for any of them.
#
# Usage:
#   scripts/action-circuit-acceptance.sh <circuit-dir>
#
# Fixtures (`Prover.toml`, `Prover.no-action.toml`) are gitignored everywhere in
# this repo. Each circuit says how to rebuild its own below.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CIRCUITS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CIRCUIT_REL="${1:-}"
if [ -z "$CIRCUIT_REL" ]; then
    echo "Usage: $0 <circuit-dir>   (e.g. giwa-attestation, arc-eligibility)"
    exit 1
fi

CIRCUIT_DIR="$CIRCUITS_ROOT/$CIRCUIT_REL"
if [ ! -d "$CIRCUIT_DIR" ]; then
    echo "No such circuit directory: $CIRCUIT_DIR"
    exit 1
fi

# The package name, read from the circuit rather than guessed from the folder:
# the two differ (`giwa-attestation` builds `giwa_attestation`).
CIRCUIT_NAME=$(grep -m1 '^name' "$CIRCUIT_DIR/Nargo.toml" | sed 's/.*= *"\(.*\)"/\1/')
TAMPER="$SCRIPT_DIR/giwa-poc/tamper-fixture.js"
VECTORS="$CIRCUIT_DIR/test-vectors"
CIRCUIT_JSON="$CIRCUIT_DIR/target/${CIRCUIT_NAME}.json"

# How this circuit rebuilds its fixtures. Both need a key and a network, so
# neither is committed and each is regenerated by the script that owns it.
case "$CIRCUIT_REL" in
    giwa-attestation)
        REGEN="$SCRIPT_DIR/giwa-poc/make-fixtures.sh"
        REGEN_NEEDS="$CIRCUITS_ROOT/.env.development"
        ;;
    arc-eligibility)
        REGEN="npx tsx $CIRCUITS_ROOT/../proofport-ai/scripts/gen-prover-toml.ts"
        REGEN_NEEDS="$CIRCUITS_ROOT/../proofport-ai/.env.test"
        ;;
    *)
        echo "No fixture recipe for $CIRCUIT_REL. Add one here rather than running it by hand."
        exit 1
        ;;
esac

cd "$CIRCUIT_DIR"
mkdir -p "$VECTORS"

# Prover.toml is gitignored repo-wide, so a fresh checkout has no fixtures.
# Rebuild them rather than reporting a failure that is really a missing file.
if [ ! -f Prover.toml ] || [ ! -f Prover.no-action.toml ]; then
  if [ -f "$REGEN_NEEDS" ]; then
    echo "  fixtures missing -- regenerating"
    $REGEN > "$VECTORS/regenerate.log" 2>&1 || {
      echo "  SKIPPED  acceptance run: could not regenerate fixtures"
      sed -n '1,12p' "$VECTORS/regenerate.log" | sed 's/^/           /'
      exit 0
    }
  else
    echo "  SKIPPED  acceptance run: $REGEN_NEEDS is absent, so no fixtures"
    exit 0
  fi
fi

PASSED=0
FAILED=0

# A fixture the circuit must accept.
accept() {
  local name="$1" prover="$2"
  if nargo execute "witness_${name}" --prover-name "$prover" > "$VECTORS/${name}.log" 2>&1; then
    echo "  ok       $name"
    PASSED=$((PASSED + 1))
  else
    echo "  FAILED   $name  (expected the circuit to accept it)"
    sed -n '1,12p' "$VECTORS/${name}.log" | sed 's/^/           /'
    FAILED=$((FAILED + 1))
  fi
}

# A fixture the circuit must refuse, WITH a named reason. Refusing for some
# other reason is a fail: it would hide the guard being gone.
refuse() {
  local name="$1" prover="$2" expected="$3"
  if nargo execute "witness_${name}" --prover-name "$prover" > "$VECTORS/${name}.log" 2>&1; then
    echo "  FAILED   $name  (the circuit ACCEPTED something it must refuse)"
    FAILED=$((FAILED + 1))
  elif grep -q "$expected" "$VECTORS/${name}.log"; then
    echo "  ok       $name  -> refused: $expected"
    PASSED=$((PASSED + 1))
  else
    echo "  FAILED   $name  (refused, but not for the stated reason)"
    echo "           wanted: $expected"
    sed -n '1,12p' "$VECTORS/${name}.log" | sed 's/^/           /'
    FAILED=$((FAILED + 1))
  fi
}

echo ""
echo "Acceptance run: $CIRCUIT_NAME"
echo ""
echo "Accepted (real attestation, both modes):"
accept "action"     "Prover"
accept "no_action"  "Prover.no-action"

echo ""
echo "Refused:"

node "$TAMPER" Prover.toml "$VECTORS/both_modes.toml" fill signal_hash > /dev/null \
  && refuse "both_modes" "test-vectors/both_modes" "signal_hash must be empty in action mode"

node "$TAMPER" Prover.toml "$VECTORS/half_action_no_hash.toml" zero action_hash > /dev/null \
  && refuse "half_action_no_hash" "test-vectors/half_action_no_hash" "action mode needs an action hash"

node "$TAMPER" Prover.toml "$VECTORS/half_action_no_domain.toml" zero domain_separator > /dev/null \
  && refuse "half_action_no_domain" "test-vectors/half_action_no_domain" "action mode needs a domain separator"

node "$TAMPER" Prover.no-action.toml "$VECTORS/nothing_signed.toml" zero signal_hash > /dev/null \
  && refuse "nothing_signed" "test-vectors/nothing_signed" "signal_hash is required when no action is bound"

node "$TAMPER" Prover.toml "$VECTORS/wrong_nullifier.toml" fill nullifier > /dev/null \
  && refuse "wrong_nullifier" "test-vectors/wrong_nullifier" "Nullifier mismatch"

# A well-formed signature over the OTHER mode's message. Not a random blob:
# this is the failure a length check or a malformed-input check would miss.
node "$TAMPER" Prover.no-action.toml "$VECTORS/signature_from_other_message.toml" copy user_signature Prover.toml > /dev/null \
  && refuse "signature_from_other_message" "test-vectors/signature_from_other_message" "Invalid user signature"

node "$TAMPER" Prover.toml "$VECTORS/wrong_signer_root.toml" fill signer_list_merkle_root > /dev/null \
  && refuse "wrong_signer_root" "test-vectors/wrong_signer_root" "Signer not in valid list"

# The real proof, end to end, for the mode that is new.
echo ""
echo "Proof (action mode):"
mkdir -p ./target/proof
if cp "./target/witness_action.gz" ./target/proof/witness.gz 2>/dev/null \
   && bb prove -b "$CIRCUIT_JSON" -w ./target/proof/witness.gz -k ./target/vk/vk -o ./target/proof --oracle_hash keccak > "$VECTORS/prove.log" 2>&1 \
   && bb verify -p ./target/proof/proof -i ./target/proof/public_inputs -k ./target/vk/vk --oracle_hash keccak >> "$VECTORS/prove.log" 2>&1; then
  echo "  ok       proved and verified ($(wc -c < ./target/proof/proof | tr -d ' ') bytes)"
  PASSED=$((PASSED + 1))
else
  echo "  FAILED   prove/verify"
  tail -12 "$VECTORS/prove.log" | sed 's/^/           /'
  FAILED=$((FAILED + 1))
fi

echo ""
echo "  $PASSED passed, $FAILED failed"
echo ""
exit $([ "$FAILED" -eq 0 ] && echo 0 || echo 1)
