[package]
name = "oidc_domain_attestation"
type = "bin"
version = "0.1.0"
authors = ["zkproofport"]

[dependencies]
jwt = { path = "../deps/noir-jwt" }
keccak256 = { tag = "v0.1.1", git = "https://github.com/noir-lang/keccak256" }
